[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder, time

; === 编译标志 (Build Flags) ===
build_flags = 
    -D DIY_BOARD               ; 自定义板子标记
    ; --- 核心参数 ---
    -D INITIAL_PPM=0           ; 频偏初始值
    -D AFC_ENABLE=1            ; 自动频率控制
    -D LED_ON=HIGH
    -D LED_OFF=LOW
    -D ADC_PIN=34              ; 电池检测脚
    -D BOARD_LED=2             ; 板载 LED
    
    ; --- LoRa 引脚  ---
    -D RADIO_CS_PIN=5
    -D RADIO_DIO0_PIN=26
    -D RADIO_RST_PIN=14
    -D RADIO_DIO1_PIN=33
    -D RADIO_BUSY_PIN=32       ; DIO2
    -D RADIO_SCLK_PIN=18
    -D RADIO_MISO_PIN=19
    -D RADIO_MOSI_PIN=23
    
    ; --- OLED 引脚 ---
    -D I2C_SDA=21              ; 代码用的是 I2C_SDA
    -D I2C_SCL=22
    -D OLED_RST=-1
    
    ; --- SD 卡引脚 ---
    -D SDCARD_CS=13            ; 代码用的是 SDCARD_CS
    -D SDCARD_SCLK=18
    -D SDCARD_MISO=19
    -D SDCARD_MOSI=23
    
    ; --- 功能开关 ---
    -D HAS_SDCARD=1            ; 代码用的是 HAS_SDCARD
    -D HAS_DISPLAY=1
    -D HAS_RTC=1
    -D HAS_PMU=0             ; 确保关掉电源管理

; === 库依赖 ===
lib_deps =
    lennarthennigs/ESP Telnet @ ^2.1.2
    olikraus/U8g2 @ ^2.35.4
    madhephaestus/ESP32AnalogRead @ ^0.2.1
    adafruit/RTClib @ ^2.1.3
    adafruit/Adafruit BusIO @ ^1.14.1
    tzapu/WiFiManager @ ^2.0.17