#ifndef LBJ_RUNTIME_CONFIG_HPP
#define LBJ_RUNTIME_CONFIG_HPP

// Keep batched CSV flushing disabled by default. Enabling it can reduce SD flush
// stalls, but a power loss may drop up to CSV_FLUSH_EVERY_N_WRITES rows or
// CSV_FLUSH_INTERVAL_MS of recent CSV data.
#ifndef ENABLE_BATCHED_CSV_FLUSH
#define ENABLE_BATCHED_CSV_FLUSH 0
#endif

#ifndef CSV_FLUSH_EVERY_N_WRITES
#define CSV_FLUSH_EVERY_N_WRITES 5
#endif

#ifndef CSV_FLUSH_INTERVAL_MS
#define CSV_FLUSH_INTERVAL_MS 5000UL
#endif

#ifndef OLED_DECODED_DISPLAY_MIN_INTERVAL_MS
#define OLED_DECODED_DISPLAY_MIN_INTERVAL_MS 150UL
#endif

#ifndef ENABLE_DECODED_SERIAL_OUTPUT
#define ENABLE_DECODED_SERIAL_OUTPUT 1
#endif

#ifndef ENABLE_DECODED_TELNET_OUTPUT
#define ENABLE_DECODED_TELNET_OUTPUT 1
#endif

#ifndef SKIP_DECODED_TELNET_WHEN_OFFLINE
#define SKIP_DECODED_TELNET_WHEN_OFFLINE 0
#endif

#ifndef ENABLE_DECODED_TELNET_RATE_LIMIT
#define ENABLE_DECODED_TELNET_RATE_LIMIT 0
#endif

#ifndef DECODED_TELNET_MIN_INTERVAL_MS
#define DECODED_TELNET_MIN_INTERVAL_MS 150UL
#endif

#ifndef DEBUG_LOG_NONE
#define DEBUG_LOG_NONE 0
#endif

#ifndef DEBUG_LOG_ERROR
#define DEBUG_LOG_ERROR 1
#endif

#ifndef DEBUG_LOG_INFO
#define DEBUG_LOG_INFO 2
#endif

#ifndef DEBUG_LOG_VERBOSE
#define DEBUG_LOG_VERBOSE 3
#endif

#ifndef DEBUG_LOG_LEVEL
#define DEBUG_LOG_LEVEL DEBUG_LOG_VERBOSE
#endif

#ifndef ENABLE_STAGE_TIMING_LOGS
#define ENABLE_STAGE_TIMING_LOGS 1
#endif

#if CSV_FLUSH_EVERY_N_WRITES < 1
#undef CSV_FLUSH_EVERY_N_WRITES
#define CSV_FLUSH_EVERY_N_WRITES 1
#endif

#if CSV_FLUSH_INTERVAL_MS < 1
#undef CSV_FLUSH_INTERVAL_MS
#define CSV_FLUSH_INTERVAL_MS 1UL
#endif

#if DECODED_TELNET_MIN_INTERVAL_MS < 1
#undef DECODED_TELNET_MIN_INTERVAL_MS
#define DECODED_TELNET_MIN_INTERVAL_MS 1UL
#endif

#endif
